Update README.md with latest - Release Links to UNPKG
sandflow/imscJS pull request #244
Opened 2023-08-30 18:01 UTC by joelBrun

unpkg will keep automatic redirect 
from https://unpkg.com/browse/imsc/dist/
to the latest published dist pakages, as of today 
it's at : https://unpkg.com/browse/imsc@1.1.3/dist/

2023-08-30 18:35 UTC, palemieux requested changes

2023-08-30 18:35 UTC, palemieux commented on README.md
> +Available builds for the release 1.1.3 are:
I think we should remove release-specific links in the README.

2023-08-30 18:35 UTC, palemieux commented on README.md
I would add a link to the releases on GitHub, which contain links to unpkg and npmjs:

https://github.com/sandflow/imscJS/releases

2023-08-31 19:16 UTC, palemieux approved these changes

2023-08-31 19:18 UTC, palemieux requested changes
"go the" -> "please consult the"

2023-09-01 04:39 UTC, joelBrun commented
Ok it is now updated.

2023-09-01 04:40 UTC, palemieux approved these changes

2023-09-01 04:40 UTC, merged