Handle space characters in fontFamily within TTML Parsing
sandflow/imscJS pull request #251
Opened 2023-12-11 16:52 UTC by mattjuggins

Closes #250 
Similar to #245, the `default` generic font family was not being correctly mapped to `monospaceSerif` if there were stray spacing characters on either side of the word, i.e. ` default`.
A solution similar to #246 is implemented using `trim()` and a unit test is provided for sanity checking.

2023-12-19 19:26 UTC, palemieux commented
@mattjuggins Ready for review?

2023-12-20 17:48 UTC, mattjuggins commented
@palemieux yep, all ready. I don't believe there's anything more to it.

2023-12-21 22:02 UTC, palemieux requested changes

2023-12-21 22:02 UTC, palemieux commented on src/test/resources/unit-tests/fontFamily.ttml
> +            <p tts:fontFamily="Arial,default">Maps 'default' value used as a fallback to 'monospaceSerif' correctly.</p>
Please align the `<p>` elements

2023-12-21 22:02 UTC, palemieux commented
@mattjuggins Looks great. Just one minor nit to fix if you do not mind.

2023-12-22 11:35 UTC, mattjuggins commented
@palemieux no problem. That should be sorted now.

2023-12-22 16:39 UTC, palemieux approved these changes

2023-12-22 16:40 UTC, merged