issue/214-es6-upgrade
sandflow/imscJS pull request #255
Opened 2024-04-27 07:02 UTC by littlespex

This PR updates the code base and build tools to ES6. It replaces jshint, browserify and closure compiler with aslant, rollup, terser and typescript (only for ES5 compilation and basic type declarations, the source files are still JS). If a full typescript conversion is desired, I can piggy back that change onto this PR.

2024-04-30 20:26 UTC, littlespex commented
@palemieux Here is base ES6 conversion. Let me know if you'd be interested in converting to TypeScript.

2024-05-01 15:41 UTC, palemieux commented
> Here is base ES6 conversion. Let me know if you'd be interested in converting to TypeScript.

Thanks @littlespex ! Will review.

2024-05-01 16:20 UTC, palemieux requested changes
I am getting the following error when running `grunt build`:

`>> [!] RollupError: dist/main/styles.js (27:37): "parseFloat" is not exported by "dist/main/utils.js", imported by "dist/main/styles.js".`

2024-05-01 16:20 UTC, palemieux commented on Gruntfile.cjs
> +                cmd: 'rollup -c rollup.config.js',
```suggestion
                cmd: 'npx rollup -c rollup.config.js',
```

2024-05-01 16:20 UTC, palemieux commented on Gruntfile.cjs
> +                cmd: 'eslint src',
```suggestion
                cmd: 'npx eslint src',
```

2024-05-01 16:20 UTC, palemieux commented on eslint.config.js
> +      'quotes': ['error', 'single', { 'avoidEscape': true, 'allowTemplateLiterals': true }],
```suggestion
      'quotes': ['error', 'double', { 'avoidEscape': true, 'allowTemplateLiterals': true }],
```

For consistency with the current codebase.

2024-05-01 16:27 UTC, palemieux requested changes

2024-05-01 16:27 UTC, palemieux commented on package.json
> +        "fix": "eslint --fix src"
```suggestion
        "fix": "npx eslint --fix src"
```

2024-05-01 16:27 UTC, palemieux commented on Gruntfile.cjs
> +                cmd: 'tsc',
```suggestion
                cmd: 'npx tsc',
```

2024-05-01 16:28 UTC, littlespex commented
Fixed the bad import and reformatted with the lint changes.

2024-05-01 16:30 UTC, palemieux commented
@littlespex Still seeing:

`>> [!] RollupError: dist/main/styles.js (27:37): "parseInt" is not exported by "dist/main/utils.js", imported by "dist/main/styles.js".`

Do you know why I would be seeing it and not you?

2024-05-01 16:31 UTC, palemieux requested changes
Still cannot build but getting closer :)

2024-05-01 16:34 UTC, littlespex commented
> @littlespex Still seeing:
> 
> `>> [!] RollupError: dist/main/styles.js (27:37): "parseInt" is not exported by "dist/main/utils.js", imported by "dist/main/styles.js".`
> 
> Do you know why I would be seeing it and not you?

Because I had local changes that I hadn't committed :)

2024-05-01 16:37 UTC, palemieux commented
@littlespex An initial objective of imscJS was to allow  `generateISD()` to be called from node since it did not contain any DOM dependencies. Would anything in the refactoring prevent this?

2024-05-01 16:45 UTC, littlespex commented
The only difference is that it would need to be imported now instead of required. I can update the build step to generate a cjs version of the library as well if you want to keep a "requirable" version of the lib.

2024-05-01 16:50 UTC, palemieux commented
> I can update the build step to generate a cjs version of the library as well if you want to keep a "requirable" version of the lib.

Let's definitely not support "require" :)

2024-05-01 16:59 UTC, palemieux commented
@littlespex I am thinking we could create a 1.2 branch using yours as a basis... we might have other improvements, e.g., factoring out XML parsing.

2024-05-01 20:02 UTC, littlespex commented
@palemieux I've added a GitHub action to run CI (lint, build, and test) for every pull request. The unit tests in `src/test/js` and `src/test/webapp/js/unit-test.js` have been converted to use node's built in test runner. The original tests have been left in place, but doesn't appear that any of them actually need to be run in a browser environment. Can we remove them in favor of the new ones?

2024-05-01 20:05 UTC, palemieux commented
> Can we remove them in favor of the new ones?

+1

2024-05-02 15:37 UTC, palemieux commented
@littlespex Ok to branch or do you have more improvements to make re: conversion to ES6 + modern tooling

2024-05-02 15:40 UTC, littlespex commented
I don't have anything else.

2024-05-02 15:51 UTC, palemieux commented
@littlespex One last request/question: can we move the `./test/*.js` under `./src/test/js` and `./test/resources/*` under `./src/test/resources/`?

2024-05-02 16:01 UTC, littlespex commented
Done

2024-05-02 16:05 UTC, palemieux commented
```
>> dist/main/main.js → dist/imsc.all.debug.js, dist/imsc.all.min.js...
>> (!) Circular dependencies
>> polyfill-node._stream_duplex.js -> polyfill-node._stream_readable.js -> polyfill-node._stream_duplex.js
>> polyfill-node._stream_duplex.js -> polyfill-node._stream_writable.js -> polyfill-node._stream_duplex.js
>> created dist/imsc.all.debug.js, dist/imsc.all.min.js in 1s
```

Is this an issue?

2024-05-02 16:18 UTC, littlespex commented
No. It's just a warning when rollup bundles the `sax` package. It resolves these correctly and bundles the "all" version of the library without error.

2024-05-02 17:21 UTC, palemieux commented
Created https://github.com/sandflow/imscJS/tree/integration/v2

2024-05-02 17:21 UTC, closed without merging